---
version: "3.3"
services:
  frittoplay-telegram-bot:
    container_name: frittoplay-telegram-bot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "frittoplay-telegram-bot:latest"
    restart: always
